/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chris' at '5/18/17 7:20 PM' with Gradle 3.1
 *
 * @author chris, @date 5/18/17 7:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
