/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chris' at '5/21/17 8:23 PM' with Gradle 3.1
 *
 * @author chris, @date 5/21/17 8:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
